#!/usr/bin/env bash

#  Copyright (C) 2020 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e


########################################
# arg parse and help log inspired from https://stackoverflow.com/questions/16483119/an-example-of-how-to-use-getopts-in-bash
usage() { echo "Usage: $0 [-s <snapshot-name-string>] " 1>&2; exit 1; }

while getopts s: flag
do
    case "${flag}" in
        s) s=${OPTARG};;
        *) usage;;
    esac
done
shift "$((OPTIND-1))"

if [ -z "${s}" ]; then
    usage
fi

########################################
START_TIME=`date +%s`
export CWD="${0%/*}"
export TESTCHAIN=$CWD/../lib/testchain
export OUT=$CWD/../out
export PORT=2000

mkdir -p $OUT
jq -S . $TESTCHAIN/out/addresses-mcd.json > $OUT/addresses-mcd.json

./../lib/testchain/scripts/launch -s default --fast --ci \
   $CWD/provision-testchain
   $CWD/create-snapshot $s --force
   

########################################
# Copy over maker-otc address
MAKER_OTC=$(cat $TESTCHAIN/out/addresses.json | jq '.MAKER_OTC')
cat $OUT/addresses-temp.json | jq ". += {MAKER_OTC: $MAKER_OTC}" > $OUT/addresses-for-keeper.json
rm $OUT/addresses-temp.json
jq -s '.[0] * .[1]' $OUT/addresses-mcd.json $OUT/addresses-for-keeper.json > $OUT/addresses-all.json

# Copy over all abis
mkdir -p $OUT/abi/scd && mkdir -p $OUT/abi/mcd
sudo cp $TESTCHAIN/out/*.abi $OUT/abi/scd
sudo cp $TESTCHAIN/out/mcd/*.abi $OUT/abi/mcd


########################################
END_TIME=`date +%s`
ELAPSED=`echo $END_TIME - $START_TIME | bc`
echo "Finished building testchain in" $ELAPSED "seconds."
