#!/usr/bin/env bash

#  Copyright (C) 2019-2020 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

START_TIME=`date +%s`
export CWD="${0%/*}"
export LIB=$CWD/../lib
export TESTCHAIN=$CWD/../lib/testchain

# VAR=$CWD/../var
# OUT=$CWD/../out

# Configure seth
export ETH_GAS=${ETH_GAS:-"7000000"} # Ganache's default block gas limit
export SETH_STATUS=yes
export ETH_RPC_ACCOUNTS=yes # Don't use ethsign
export ETH_RPC_URL=http://127.1:2000

# Spin up testchain, provision it, and run tests against it before shutting down
./../lib/testchain/scripts/launch -s default --fast --throw-revert --ci \
   $CWD/provision-testchain
   $CWD/run-tests

# ./../lib/testchain/scripts/launch -s default --fast


END_TIME=`date +%s`
ELAPSED=`echo $END_TIME - $START_TIME | bc`
echo "Finished tests in" $ELAPSED "seconds."
